FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

ENV PIP_BREAK_SYSTEM_PACKAGES=1

RUN apt-get update \
  && apt-get install -y python3-pip python3-dev \
  && cd /usr/local/bin \
  && ln -s /usr/bin/python3 python \
  && pip3 --no-cache-dir install --upgrade pip \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /sandbox

COPY requirements.txt /sandbox
RUN pip3 install -r requirements.txt

COPY container_setup/mysql.sh /sandbox
COPY container_setup/docker-entrypoint.sh /usr/local/bin

RUN bash mysql.sh

# Make the entrypoint script executable
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

# Use your entrypoint script
ENTRYPOINT ["docker-entrypoint.sh"]

COPY python_executor.py /sandbox

COPY checkpoints/database_dump.sql /sandbox
