name: Python Formatting Check

on: [push, pull_request]

jobs:
  format-check:
    name: Check Python Formatting
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
        
      - name: Install Dependencies
        run: |
          pip install flake8 black ruff
        
      - name: Check Formatting with Flake8
        run: flake8
        continue-on-error: true
        
      - name: Check Formatting with Black
        run: black --check .
        continue-on-error: true
        
      - name: Check Formatting with Ruff
        run: ruff check
        continue-on-error: true